USE mydb;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE INSUMO_UTILIZADO;
TRUNCATE TABLE DETALLE_RECETA;
TRUNCATE TABLE ATENCION_TRATAMIENTO;
TRUNCATE TABLE ATENCION_DIAGNOSTICO;
TRUNCATE TABLE RECETA;
TRUNCATE TABLE DETALLE_BOLETA_SERV;
TRUNCATE TABLE DETALLE_CITA;
TRUNCATE TABLE ATENCION_MEDICA;
TRUNCATE TABLE DETALLE_BOLETA_ART;
TRUNCATE TABLE CITA;
TRUNCATE TABLE HORARIO_VETERINARIO;
TRUNCATE TABLE HORARIO_ADMINISTRADOR;
TRUNCATE TABLE BOLETA;
TRUNCATE TABLE MASCOTA;
TRUNCATE TABLE ARTICULO;
TRUNCATE TABLE VETERINARIO;
TRUNCATE TABLE ADMINISTRADOR;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE TRATAMIENTO;
TRUNCATE TABLE DIAGNOSTICO;
TRUNCATE TABLE SERVICIO;
TRUNCATE TABLE CATEGORIA_ARTICULO;
TRUNCATE TABLE HORARIO;
TRUNCATE TABLE CUENTA;

SET FOREIGN_KEY_CHECKS = 1;
