-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 14:47:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema prog3
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CUENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA` (
  `idCuenta` INT NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `fechaCreacion` DATE NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCliente` INT NOT NULL,
  `idCuenta` INT NOT NULL,
  `dni` INT NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(9) NULL,
  INDEX `IDX_CLIENTE_CUENTA` (`idCuenta` ASC) INVISIBLE,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCuenta_UNIQUE` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_CUENTA`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`CUENTA` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MASCOTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MASCOTA` (
  `idMascota` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `peso` DECIMAL(5,2) NULL,
  `fechaNacimiento` DATE NULL,
  `tipoMascota` CHAR(1) NULL,
  `raza` VARCHAR(45) NULL,
  PRIMARY KEY (`idMascota`),
  INDEX `fk_MASCOTA_CLIENTE1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_MASCOTA_CLIENTE1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO` (
  `idHorario` INT NOT NULL,
  `diaSemana` VARCHAR(10) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRADOR` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `dni` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_ADMINISTRADOR_CUENTA1_idx` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `idCuenta_UNIQUE` (`idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINISTRADOR_CUENTA1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`CUENTA` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTILISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTILISTA` (
  `idEstilista` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `idCuenta` INT NOT NULL,
  `dni` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `estado` TINYINT(1) NULL,
  `certificacionGrooming` VARCHAR(45) NULL,
  `especialidadAnimal` CHAR(1) NULL,
  PRIMARY KEY (`idEstilista`),
  INDEX `fk_ESTILISTA_CUENTA1_idx` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `idCuenta_UNIQUE` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `idCuenta_UNIQUE` (`idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_ESTILISTA_CUENTA1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`CUENTA` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VETERINARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VETERINARIO` (
  `idVeterinario` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `dni` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `estado` TINYINT(1) NULL,
  `numeroColegiatura` VARCHAR(45) NULL,
  `especialidadMedica` CHAR(1) NULL,
  PRIMARY KEY (`idVeterinario`),
  INDEX `fk_VETERINARIO_CUENTA1_idx` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `idCuenta_UNIQUE` (`idCuenta` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIO_CUENTA1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `mydb`.`CUENTA` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOLETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BOLETA` (
  `idBoleta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `total` DECIMAL NOT NULL,
  `metodoPago` ENUM('Efectivo', 'Tarjeta de credito') NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idBoleta`),
  INDEX `fk_BOLETA_CLIENTE1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_BOLETA_CLIENTE1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA_ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA_ARTICULO` (
  `idCategoriaArticulo` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoriaArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ARTICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ARTICULO` (
  `idArticulo` INT NOT NULL,
  `idCategoriaArticulo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precioBase` DECIMAL NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NOT NULL,
  `stockActual` INT NOT NULL,
  `stockMinimo` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_ARTICULO_CategoriaArticulo1_idx` (`idCategoriaArticulo` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICULO_CategoriaArticulo1`
    FOREIGN KEY (`idCategoriaArticulo`)
    REFERENCES `mydb`.`CATEGORIA_ARTICULO` (`idCategoriaArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_BOLETA_ART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_BOLETA_ART` (
  `idDetalleBoletaArti` INT NOT NULL,
  `idBoleta` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` DECIMAL NULL,
  PRIMARY KEY (`idDetalleBoletaArti`),
  INDEX `fk_DETALLE_ARTICULO_BOLETA_ARTICULO1_idx` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_BOLETA_BOLETA1`
    FOREIGN KEY (`idBoleta`)
    REFERENCES `mydb`.`BOLETA` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_ARTICULO_BOLETA_ARTICULO1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `mydb`.`ARTICULO` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITA_MEDICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITA_MEDICA` (
  `idCita` INT NOT NULL,
  `idMascota` INT NOT NULL,
  `idVeterinario` INT NOT NULL,
  `fechaHora` DATETIME NULL,
  `estado` ENUM('Pendiente', 'Aprobado', 'Rechazado') NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_CITA_MEDICA_VETERINARIO1_idx` (`idVeterinario` ASC) VISIBLE,
  INDEX `fk_CITA_MEDICA_MASCOTA1_idx` (`idMascota` ASC) VISIBLE,
  CONSTRAINT `fk_CITA_MEDICA_VETERINARIO1`
    FOREIGN KEY (`idVeterinario`)
    REFERENCES `mydb`.`VETERINARIO` (`idVeterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_MEDICA_MASCOTA1`
    FOREIGN KEY (`idMascota`)
    REFERENCES `mydb`.`MASCOTA` (`idMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATENCION_MEDICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATENCION_MEDICA` (
  `idAtencionMedica` INT NOT NULL,
  `idMascota` INT NOT NULL,
  `idCitaMedica` INT NOT NULL,
  `fechaHora` DATETIME NULL,
  `motivoConsulta` VARCHAR(45) NULL,
  `pesoFisico` DECIMAL NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtencionMedica`),
  INDEX `fk_ATENCION_MEDICA_MASCOTA1_idx` (`idMascota` ASC) VISIBLE,
  INDEX `fk_ATENCION_MEDICA_CITA_MEDICA1_idx` (`idCitaMedica` ASC) VISIBLE,
  CONSTRAINT `fk_ATENCION_MEDICA_MASCOTA1`
    FOREIGN KEY (`idMascota`)
    REFERENCES `mydb`.`MASCOTA` (`idMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATENCION_MEDICA_CITA_MEDICA1`
    FOREIGN KEY (`idCitaMedica`)
    REFERENCES `mydb`.`CITA_MEDICA` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECETA` (
  `idReceta` INT NOT NULL,
  `idAtencionMedica` INT NOT NULL,
  `fechaEmision` DATE NULL,
  `indicacionesGenerales` VARCHAR(500) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idReceta`),
  INDEX `fk_RECETA_ATENCION_MEDICA1_idx` (`idAtencionMedica` ASC) VISIBLE,
  CONSTRAINT `fk_RECETA_ATENCION_MEDICA1`
    FOREIGN KEY (`idAtencionMedica`)
    REFERENCES `mydb`.`ATENCION_MEDICA` (`idAtencionMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_RECETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_RECETA` (
  `idDetalleReceta` INT NOT NULL,
  `idReceta` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `dosis` VARCHAR(45) NULL,
  `frecuencia` VARCHAR(45) NULL,
  `duracionDias` INT NULL,
  `cantidadTotal` INT NULL,
  PRIMARY KEY (`idDetalleReceta`),
  INDEX `fk_DETALLE_RECETA_RECETA1_idx` (`idReceta` ASC) VISIBLE,
  INDEX `fk_DETALLE_RECETA_ARTICULO1_idx` (`idArticulo` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_RECETA_RECETA1`
    FOREIGN KEY (`idReceta`)
    REFERENCES `mydb`.`RECETA` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_RECETA_ARTICULO1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `mydb`.`ARTICULO` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIO_MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIO_MEDICO` (
  `idServicioMedico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precioBase` DECIMAL NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  `duracionEstimada` INT NULL,
  `tipoServicioMedico` ENUM('Consulta médica', 'Operación', 'Vacunación', 'Emergencia') NULL,
  `requiereTriaje` TINYINT(1) NULL,
  `requiereVacuna` TINYINT(1) NULL,
  PRIMARY KEY (`idServicioMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_CITA_MEDICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_CITA_MEDICA` (
  `idDetalleCitaMedica` INT NOT NULL,
  `idServicioMedico` INT NOT NULL,
  `idCita` INT NOT NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idDetalleCitaMedica`),
  INDEX `fk_DETALLE_CITA_MEDICA_CITA_MEDICA1_idx` (`idCita` ASC) VISIBLE,
  INDEX `fk_DETALLE_CITA_MEDICA_SERVICIO_MEDICO1_idx` (`idServicioMedico` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_CITA_MEDICA_CITA_MEDICA1`
    FOREIGN KEY (`idCita`)
    REFERENCES `mydb`.`CITA_MEDICA` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_CITA_MEDICA_SERVICIO_MEDICO1`
    FOREIGN KEY (`idServicioMedico`)
    REFERENCES `mydb`.`SERVICIO_MEDICO` (`idServicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIO_ESTETICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIO_ESTETICO` (
  `idServicioEstetico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precioBase` DECIMAL NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  `duracionEstimada` INT NULL,
  `tipoServicioEstetico` ENUM('Baño completo', 'Corte de pelo y estilismo', 'Corte de uñas', 'Cepillado y deslanado') NULL,
  PRIMARY KEY (`idServicioEstetico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIAGNOSTICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIAGNOSTICO` (
  `idDiagnostico` INT NOT NULL,
  `nombreEnfermedad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiagnostico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRATAMIENTO` (
  `idTratamiento` INT NOT NULL,
  `nombreProcedimiento` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTratamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITA_ESTETICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITA_ESTETICA` (
  `idCita` INT NOT NULL,
  `idMascota` INT NOT NULL,
  `idEstilista` INT NOT NULL,
  `fechaHora` DATETIME NULL,
  `estado` ENUM('Pendiente', 'Aprobado', 'Rechazado') NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_CITA_ESTETICA_MASCOTA1_idx` (`idMascota` ASC) VISIBLE,
  INDEX `fk_CITA_ESTETICA_ESTILISTA1_idx` (`idEstilista` ASC) VISIBLE,
  CONSTRAINT `fk_CITA_ESTETICA_MASCOTA1`
    FOREIGN KEY (`idMascota`)
    REFERENCES `mydb`.`MASCOTA` (`idMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_ESTETICA_ESTILISTA1`
    FOREIGN KEY (`idEstilista`)
    REFERENCES `mydb`.`ESTILISTA` (`idEstilista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIO_ESTETICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIO_ESTETICO` (
  `idServicioEstetico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precioBase` DECIMAL NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  `duracionEstimada` INT NULL,
  `tipoServicioEstetico` ENUM('Baño completo', 'Corte de pelo y estilismo', 'Corte de uñas', 'Cepillado y deslanado') NULL,
  PRIMARY KEY (`idServicioEstetico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_CITA_ESTETICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_CITA_ESTETICA` (
  `idDetalleCitaEstetica` INT NOT NULL,
  `idServicioEstetico` INT NOT NULL,
  `idCita` INT NOT NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idDetalleCitaEstetica`),
  INDEX `fk_DETALLE_CITA_ESTETICA_CITA_ESTETICA1_idx` (`idCita` ASC) VISIBLE,
  INDEX `fk_DETALLE_CITA_ESTETICA_SERVICIO_ESTETICO1_idx` (`idServicioEstetico` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_CITA_ESTETICA_CITA_ESTETICA1`
    FOREIGN KEY (`idCita`)
    REFERENCES `mydb`.`CITA_ESTETICA` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_CITA_ESTETICA_SERVICIO_ESTETICO1`
    FOREIGN KEY (`idServicioEstetico`)
    REFERENCES `mydb`.`SERVICIO_ESTETICO` (`idServicioEstetico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_BOLETA_SERV_MED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_BOLETA_SERV_MED` (
  `idDetalleBoletaServMedi` INT NOT NULL,
  `idBoleta` INT NOT NULL,
  `idServicioMedico` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` DECIMAL NULL,
  PRIMARY KEY (`idDetalleBoletaServMedi`),
  INDEX `fk_DETALLE_BOLETA_SERV_MEDI_SERVICIO_MEDICO1_idx` (`idServicioMedico` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_BOLETA_BOLETA10`
    FOREIGN KEY (`idBoleta`)
    REFERENCES `mydb`.`BOLETA` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_BOLETA_SERV_MEDI_SERVICIO_MEDICO1`
    FOREIGN KEY (`idServicioMedico`)
    REFERENCES `mydb`.`SERVICIO_MEDICO` (`idServicioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_BOLETA_SERV_EST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_BOLETA_SERV_EST` (
  `idDetalleBoletaServEst` INT NOT NULL,
  `idBoleta` INT NOT NULL,
  `idServicioEstetico` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` DECIMAL NULL,
  INDEX `fk_DETALLE_BOLETA_SERV_EST_SERVICIO_ESTETICO1_idx` (`idServicioEstetico` ASC) VISIBLE,
  PRIMARY KEY (`idDetalleBoletaServEst`),
  CONSTRAINT `fk_DETALLE_BOLETA_BOLETA100`
    FOREIGN KEY (`idBoleta`)
    REFERENCES `mydb`.`BOLETA` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_BOLETA_SERV_EST_SERVICIO_ESTETICO1`
    FOREIGN KEY (`idServicioEstetico`)
    REFERENCES `mydb`.`SERVICIO_ESTETICO` (`idServicioEstetico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATENCION_DIAGNOSTICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATENCION_DIAGNOSTICO` (
  `idAtencionMedica` INT NOT NULL,
  `idDiagnostico` INT NOT NULL,
  `nivelGravedad` VARCHAR(45) NULL,
  `detalleDiagnostico` VARCHAR(200) NULL,
  PRIMARY KEY (`idDiagnostico`, `idAtencionMedica`),
  INDEX `fk_ATENCION_DIAGNOSTICO_ATENCION_MEDICA1_idx` (`idAtencionMedica` ASC) VISIBLE,
  INDEX `fk_ATENCION_DIAGNOSTICO_DIAGNOSTICO1_idx` (`idDiagnostico` ASC) VISIBLE,
  CONSTRAINT `fk_ATENCION_DIAGNOSTICO_ATENCION_MEDICA1`
    FOREIGN KEY (`idAtencionMedica`)
    REFERENCES `mydb`.`ATENCION_MEDICA` (`idAtencionMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATENCION_DIAGNOSTICO_DIAGNOSTICO1`
    FOREIGN KEY (`idDiagnostico`)
    REFERENCES `mydb`.`DIAGNOSTICO` (`idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATENCION_TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATENCION_TRATAMIENTO` (
  `idAtencionTratamiento` INT NOT NULL,
  `idAtencionMedica` INT NOT NULL,
  `idTratamiento` INT NOT NULL,
  PRIMARY KEY (`idAtencionTratamiento`),
  INDEX `fk_ATENCION_TRATAMIENTO_TRATAMIENTO1_idx` (`idTratamiento` ASC) VISIBLE,
  INDEX `fk_ATENCION_TRATAMIENTO_ATENCION_MEDICA1_idx` (`idAtencionMedica` ASC) VISIBLE,
  CONSTRAINT `fk_ATENCION_TRATAMIENTO_TRATAMIENTO1`
    FOREIGN KEY (`idTratamiento`)
    REFERENCES `mydb`.`TRATAMIENTO` (`idTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATENCION_TRATAMIENTO_ATENCION_MEDICA1`
    FOREIGN KEY (`idAtencionMedica`)
    REFERENCES `mydb`.`ATENCION_MEDICA` (`idAtencionMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONAL_ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONAL_ADMINISTRADOR` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO_ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO_ADMINISTRADOR` (
  `idAdministradorHorario` INT NOT NULL,
  `idAdministrador` INT NOT NULL,
  `idHorario` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idAdministradorHorario`),
  INDEX `fk_ADMINISTRADOR_HORARIO_ADMINISTRADOR1_idx` (`idAdministrador` ASC) VISIBLE,
  INDEX `fk_ADMINISTRADOR_HORARIO_HORARIO1_idx` (`idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINISTRADOR_HORARIO_ADMINISTRADOR1`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `mydb`.`ADMINISTRADOR` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINISTRADOR_HORARIO_HORARIO1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `mydb`.`HORARIO` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO_ESTILISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO_ESTILISTA` (
  `idEstilistaHorario` INT NOT NULL,
  `idEstilista` INT NOT NULL,
  `idHorario` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idEstilistaHorario`),
  INDEX `fk_ESTILISTA_HORARIO_ESTILISTA1_idx` (`idEstilista` ASC) VISIBLE,
  INDEX `fk_ESTILISTA_HORARIO_HORARIO1_idx` (`idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_ESTILISTA_HORARIO_ESTILISTA1`
    FOREIGN KEY (`idEstilista`)
    REFERENCES `mydb`.`ESTILISTA` (`idEstilista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILISTA_HORARIO_HORARIO1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `mydb`.`HORARIO` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO_VETERINARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO_VETERINARIO` (
  `idVeterinarioHorario` INT NOT NULL,
  `idVeterinario` INT NOT NULL,
  `idHorario` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idVeterinarioHorario`),
  INDEX `fk_VETERINARIO_HORARIO_VETERINARIO1_idx` (`idVeterinario` ASC) VISIBLE,
  INDEX `fk_VETERINARIO_HORARIO_HORARIO1_idx` (`idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIO_HORARIO_VETERINARIO1`
    FOREIGN KEY (`idVeterinario`)
    REFERENCES `mydb`.`VETERINARIO` (`idVeterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VETERINARIO_HORARIO_HORARIO1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `mydb`.`HORARIO` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSUMO_UTILIZADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSUMO_UTILIZADO` (
  `idInsumoUtilizado` INT NOT NULL,
  `idAtencionTratamiento` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidadUtilizada` INT NOT NULL,
  PRIMARY KEY (`idInsumoUtilizado`),
  INDEX `fk_INSUMO_UTILIZADO_ARTICULO1_idx` (`idArticulo` ASC) VISIBLE,
  INDEX `fk_INSUMO_UTILIZADO_ATENCION_TRATAMIENTO1_idx` (`idAtencionTratamiento` ASC) VISIBLE,
  CONSTRAINT `fk_INSUMO_UTILIZADO_ARTICULO1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `mydb`.`ARTICULO` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSUMO_UTILIZADO_ATENCION_TRATAMIENTO1`
    FOREIGN KEY (`idAtencionTratamiento`)
    REFERENCES `mydb`.`ATENCION_TRATAMIENTO` (`idAtencionTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
